category: API
description: Strive is a client for the Strava V3 API.
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options:
- -Wall
github: tfausak/strive
library:
  dependencies:
  - aeson >=0.7 && <0.12
  - base ==4.*
  - bytestring ==0.10.*
  - data-default ==0.5.*
  - gpolyline ==0.1.*
  - http-conduit ==2.*
  - http-types >=0.8 && <0.10
  - template-haskell ==2.*
  - text >=0.11 && <2
  - time ==1.*
  - transformers >=0.3 && <0.5
  source-dirs: library
license: MIT
maintainer: Taylor Fausak
name: strive
synopsis: A client for the Strava V3 API.
tests:
  readme:
    dependencies:
    - base
    - bytestring
    - markdown-unlit >=0.2 && <0.6
    - strive
    - time
    ghc-options:
    - -pgmL markdown-unlit
    main: README.lhs
version: '2.2.0'
