category: API
description: Strive is a client for the Strava V3 API.
extra-source-files:
- CHANGELOG.md
- package.yaml
- README.md
- stack.yaml
ghc-options:
- -Wall
github: tfausak/strive
library:
  dependencies:
  - aeson >=0.11 && <1.3
  - base ==4.9.*
  - bytestring ==0.10.*
  - data-default ==0.7.*
  - gpolyline ==0.1.*
  - http-client >=0.4.30 && <0.6
  - http-client-tls >=0.2 && <0.4
  - http-types ==0.9.*
  - template-haskell ==2.11.*
  - text ==1.2.*
  - time ==1.6.*
  - transformers ==0.5.*
  source-dirs: library
license: MIT
maintainer: Taylor Fausak
name: strive
synopsis: A client for the Strava V3 API.
tests:
  readme:
    dependencies:
    - base
    - bytestring
    - markdown-unlit ==0.4.*
    - strive
    - time
    ghc-options:
    - -pgmL markdown-unlit
    main: README.lhs
version: '3.0.3'
